#apiVersion: v1
#kind: Secret
#metadata:
#  name: private-repo
#  namespace: argocd
#  labels:
#    argocd.argoproj.io/secret-type: repository
#stringData:
#  type: git
#  url: https://github.com/dgeorgik/TestArgoCDProject.git
#  password: my-password
#  username: my-username

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort